# <center>TSI1 - Informatique tronc commun S2 (ITC2) - 2023-2024<br/></center>
# <center>TD pour l'apprentissage et la manipulation des graphes<br/>(limitation aux graphes simples)</center>
## <center>— Questionnaire du sujet (V 1.3 du 02-07-2024) —<br/>— et éléments de corrigé —</center>
-----
## Plan du document

**Préambule : quelques rappels**
- Syntaxe employée pour la définition des fonctions
- Précisions sur le vocabulaire employé
- Rappels sur le vocabulaire des graphes
- Quelques fonctions utiles
    - Fonction de vérification d'un objet de nature matricielle
    - Fonction d'affichage des termes d'une matrice Python
    - Fonction de vérification qu'une matrice est carrée
    - Fonction de transposition de matrice

**I. Analyse de graphes à partir d'exemples**

I.1 Présentation des graphes exemples<br/>
I.2 Représentation, codage et traitements des graphes non-orientés<br/>
I.2.1 Usage d'une liste<br/>
I.2.2 Usage d'un dictionnaire<br/>
I.2.3 Usage de matrices<br/>
I.2.4 Fonctions de traitement des graphes non-orientés<br/>
I.2.4.1 liste d'adjacence vs. matrice d'adjacence<br/>
I.2.4.2 liste et matrice d'adjacence vs. liste des arêtes<br/>
I.2.4.3 Construction de la matrice d’incidence<br/>
I.2.5 Bilan, conclusion<br/>
I.3 Représentation, codage et traitements des graphes orientés<br/>
I.3.1 Liste d'adjacence<br/>
I.3.2 Dictionnaire d'adjacence<br/>
I.3.3 Matrice d'adjacence<br/>
I.3.4 Matrice d'incidence<br/>
I.3.5 Fonctions de traitement des graphes orientés<br/>
I.3.5.1 Construction de la matrice d'adjacence<br/>
I.3.5.2 Construction de la liste des arêtes<br/>
I.3.5.3 Construction de la matrice d’incidence

**II. Fonctions de caractérisation des graphes**<br/>
II.1 Symétrie de la matrice d'adjacence d'un graphe non-orienté<br/>
II.2 Détection de la cohérence d'un graphe (orienté ou pas) par sa matrice d'incidence
II.3 Caractéristiques des sommets d’un graphe

# Préambule : quelques rappels

## Syntaxe employée pour la définition des fonctions
En Python, une fonction est définie à la suite du mot-clé `def` suivi des arguments placés entre parenthèses. Elle est cloturée par le mot-clé `return` suivi du n-uplet (tuple) des variables évaluées qui sont *renvoyés*, c'est à dire dont le contenu de chacune d'elle sera transmis lorsque la fonction sera appelée.

Pour formaliser sa définition, la fonction protype précise précise son identifiant (son nom) et les arguments qui lui sont nécessaires associés à leur type, conformément à cet exemple :

`def maFonction`(**n**:`int`, **X**:[`float`], **c**:`str`, **u**) -> (`int`, `np.ndarray`, `[float]`):

Ce qui signifie que la fonction `maFonction` prend quatre arguments :

* le premier (**n**) est un entier (type `int`),
* le deuxième (**X**) une liste (type `list`) de nombres à virgule flottante (type `float`),
* le troisième (**c**) une chaîne de caractères (type `str`)
* et le type du dernier (**u**) n’est pas précisé.

## Précisions sur le vocabulaire employé
- Un **objet** Python est une entité qui dispose d'un contenu et d'un type. Une **variable** est un autre nom pour signifier objet.

- Un **type** Python est une caractéristique commune à tous les objets d'une même catégorie. Par exemple, les entiers sont de type `int` (pour *integer*), les nombres à virgule ou flottants sont de type `float`, les caractères (*char*) et les chaînes de caractères (*string*) sont de type `str`.

- Une **séquence** représente une suite itérable d'éléments (qui peuvent être comptés) et indiçable (dont le rang des éléments est repéré par un indice démarrant le plus souvent à 0 en Python). Ainsi, un **n-uplet** (ou **tuple**) d’entiers (ex. `(1, 2, 3)`) et une liste d’entiers (ex. `[1, 2, 3]`) sont des **séquences d’entiers**. Pour cette étude, un objet Python, ou variable, qui n'est pas une séquence est appelé **scalaire**. Un scalaire ne peut être décomposé alors qu'une séquence l'est en ses éléments.

- Une **liste** Python est une séquence comportant des éléments de tous types (des entiers, des flottants, des caractères, des chaînes de caractères et même d'autres listes). Une liste est un objet de type `list`. **Il ne faut donc pas confondre l'objet *liste* et son type `list`**, même si dans la pratique les références aux deux appellations sont souvent confondues.

- Des **types compatibles** caractérisent des éléments qui peuvent être combinés par des opérations alors qu'ils ne sont pas de même type. Par exemple, les types `int` et `float` sont compatibles car il est possible d'effectuer la somme `2 + 3.14` ou le produit `3 * 4.1` alors que les opérandes sont des entiers et des flottants. Il en va de même pour les caractères et les chaînes de caractères, mais qui sont au final des objets de même type `str`.

- Quand un objet est de type `int` ou `float`, le type mentionné par `int|float` où le caractère `|` est l'**opérateur logique ou** (**or** en anglais).

## Rappels sur le vocabulaire des graphes
### Sommets adjacents
Pour rappel, le terme « **adjacence** » se réfère aux **sommets d'un graphe**. Dire de **deux sommets** qu'ils **sont adjacents** signifie qu'ils sont **reliés par une arête** (figure 1).

<center><img src="illustrations/fig01_adjacence.pdf"><br>
Figure 1 – Illustration de l'adjacence de deux sommets.</center>

>Si le **graphe** est **non-orienté** (figure 1, à gauche) l'adjacence est réciproque : `1` est adjacent à `2` tout comme `2` est adjacent à `1`.
>
>Si le **graphe** est **orienté** (figure 1, à droite) l'adjacence dépend du sens de l'arête (sens de la flèche) : `2` est adjacent à `1` car l'arête va de `1` vers `2` (on pourrait dire que `1` « voit » `2`). Par contre `2` n'est pas adjacent à `1` car l'arête ne vient pas de `2` (`2` ne voit pas `1`).

### Arêtes incidentes
Pour rappel, le terme « **incidence** » se réfère aux **arêtes d'un graphe**. Dire d'**une arête** qu'elle **est incidente à un sommet signifie qu'elle indique une relation avec lui** (figure 1).

>Si le **graphe** est **non-orienté** (figure 1, à gauche) : l'arête est incidente aux deux sommets `1` et `2`.
>
>Si le **graphe** est **orienté** (figure 1, à droite) l'incidence dépend du sens de l'arête (sens de la flèche) : l'arête est **incidente entrante** au sommet `2` car elle se dirige vers lui (`2` est la destination) et l'arête est **incidente sortante** au sommet `1` car elle en provient (`1` est l'origine).

## Quelques fonctions utiles
### Fonction de vérification d'un objet de nature matricielle

La fonction dont le protype est le suivant :

`def isMatrix(U:list of list) -> bool:`

renvoit `True` si `U` est une matrice et `False` sinon.

Un script (possible) de cette fonction est le suivant :

In [7]:
def isMatrix(U):
    if U in ([], [[]]): # Cas de rejets possibles
        return False # Listes sans éléments != matrice ou matrice ligne
    for u in U: # Vérification que les éléments de U sont des listes
        if type(u) != list: # Pas des listes
            return False
        if len(u) != len(U[0]): # Vérification des tailles
            return False        
    return True

In [8]:
# Essais de isMatrix()
M1 = [[1, 2], [3, 4]]
print(M1, 'matrice ?', end=' ') ; print(isMatrix(M1)) # Renvoie True
lst2 = [[10, -3, 0], [3, 4]]
print(lst2, 'matrice ?', end=' ') ; print(isMatrix(lst2)) # Renvoie False
lst3 = [[10, -3, 0], [3, 4], 5]
print(lst3, 'matrice ?', end=' ') ; print(isMatrix(lst3)) # Renvoie False

[[1, 2], [3, 4]] matrice ? True
[[10, -3, 0], [3, 4]] matrice ? False
[[10, -3, 0], [3, 4], 5] matrice ? False


### Fonction d'affichage des termes d'une matrice Python
La fonction dont le protype est le suivant :

`def matrixDisplay(U:matrix):`

reçoit a priori une matrice `U`, mais ne renvoie aucune donnée. Elle permet d'afficher la matrice `U` ligne par ligne en alignant les termes grâce à une tabulation (caractère `\t`) pour former des colonnes espacées.

Avant tout affichage, la fonction vérifie que l'argument `U` est de type `matrix` en utilisant la fonction `isMatrix()`. Si ce n'est pas le cas, la fonction affiche uniquement "L'argument de la fonction n'est pas une matrice.", puis elle s'interrompt.

In [9]:
def matrixDisplay(U): # Rem : fonctionne aussi si M n'est pas une matrice
    if not isMatrix(U):
        print('matrixDisplay -', "L'argument de la fonction n'est pas une matrice.")
        return
    if isMatrix(U):
        for l in U:
            for e in l:
                print(e, end='\t')
            print()
        return
    print() # Pour rétablir un affichage "à la ligne"
    # L'absence de return n'est pas une erreur : c'est équivalent à "return None"

In [10]:
# Essais de matrixDisplay()
M1 = [[1, 2], [3, 4]]
print('Avec la matrice', M1, ':')
matrixDisplay(M1)
M2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print('Avec la matrice', M2, ':')
matrixDisplay(M2)
lst1 = [[10, -3, 0], [3, 4]]
print('Avec la liste', lst1, ':')
matrixDisplay(lst1)
lst2 = [[10, -3, 0], [3, 4], 5]
print('Avec la liste', lst2, ':')
matrixDisplay(lst2)

Avec la matrice [[1, 2], [3, 4]] :
1	2	
3	4	
Avec la matrice [[1, 2, 3], [4, 5, 6], [7, 8, 9]] :
1	2	3	
4	5	6	
7	8	9	
Avec la liste [[10, -3, 0], [3, 4]] :
matrixDisplay - L'argument de la fonction n'est pas une matrice.
Avec la liste [[10, -3, 0], [3, 4], 5] :
matrixDisplay - L'argument de la fonction n'est pas une matrice.


### Fonction de vérification qu'une matrice est carrée

La fonction dont le protype est le suivant :

`def isMatrixSquare(U:matrix) -> bool:`

renvoit `True` si est utilisée dans le script de cette fonction.

La fonction de protype :

`def isMatrix(U:list of list) -> bool:`

renvoit `True` si `U` est une matrice carré et `False` sinon.

Un script (possible) et très condensé de cette fonction est le suivant :

In [11]:
def isMatrixSquare(U): # Version très condensée
    return len(U) == len(U[0]) and isMatrix(U)

In [12]:
# Essais isMatrixSquare() (illustrations)
lst = [[10, -3, 0], [3, 4]]
print(lst, 'carrée ?', isMatrixSquare(lst)) # Renvoie False
M1 = [[1, 2], [3, 4]]
print(M1, 'carrée ?', isMatrixSquare(M1)) # Renvoie True
M2 = [[10, -3, 0], [3, 4, 1]]
print(M2, 'carrée ?', isMatrixSquare(M2)) # Renvoie False
M3 = [[1, 2], 3, 4]
print(M3, 'carrée ?', isMatrixSquare(M3)) # Renvoie False
M4 = [[10]]
print(M4, 'carrée ?', isMatrixSquare(M4)) # Renvoie True

[[10, -3, 0], [3, 4]] carrée ? False
[[1, 2], [3, 4]] carrée ? True
[[10, -3, 0], [3, 4, 1]] carrée ? False
[[1, 2], 3, 4] carrée ? False
[[10]] carrée ? True


###  Fonction de transposition de matrice
La fonction de protype :

`def matrixTranspose(U:matrix) -> matrix:`

renvoit la matrice transposée de `U` et `None` si l'argument n'est pas une matrice en employant la fonction `isMatrix()` dans le script de cette fonction.

Un script (possible) et très condensé de cette fonction est le suivant :

In [13]:
def matrixTranspose(U):
    if not isMatrix(U): # Vérifications
        print('Transpose -', U, "L'argument de la fonction n'est pas une matrice.") # Facultatif
        return
    Ut = [] # Création de la matrice transposée (nouvelle liste)
    V = list(U) # Duplication de l'argument avant traitements car il est global
    if not isMatrixSquare(V): # Si matrice rectangulaire
        for j in range(len(V[0])): # Scrutation des indices de colonnes
            lgn = [] # Initialisation de la ligne courante
            for i in range(len(V)): # Remplissage...
                lgn.append(V[i][j]) # ... de la ligne courante
            Ut.append(lgn) # Ajout de la ligne courante à la transposée en cours
    else: # Si matrice carrée
        Ut = list(U) # Duplication de l'argument (avec écrasement de Ut vide)
        for i in range(len(Ut)): # Scrutation des indices de lignes
            for j in range(i, len(Ut)): # Scrutation des indices de colonnes non déjà traités
                Ut[i][j], Ut[j][i] = Ut[j][i], Ut[i][j] # Echanges % diagonale
    return Ut # Pas nécessaire avec les matrices qui sont des listes, donc globales

In [14]:
# Essais de matrixTranspose() (illustrations)
M1 = [[1, 2], [3, 4]]
print('La transposée de', M1, end=' ')
print('est :', matrixTranspose(M1)) # Renvoie [[1, 3], [2, 4]]
M2 = [[10, -3, 0], [3, 4, 1]]
print('La transposée de', M2, end=' ')
print('est :', matrixTranspose(M2)) # Renvoie [[10, 3], [-3, 4], [0, 1]]
M3 = [list(range(6))]
print('La transposée de', M3, end=' ')
print('est :', matrixTranspose(M3)) # Renvoie [[0], [1], [2], [3], [4], [5]]
M4 = matrixTranspose(M3)
print('La transposée de', M4, end=' ')
print('est :', matrixTranspose(M4)) # Renvoie [0, 1, 2, 3, 4, 5]
M5 = [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
print('La transposée de', M5, end=' ')
print( 'est :', matrixTranspose(M5)) # Renvoie ....

La transposée de [[1, 2], [3, 4]] est : [[1, 3], [2, 4]]
La transposée de [[10, -3, 0], [3, 4, 1]] est : [[10, 3], [-3, 4], [0, 1]]
La transposée de [[0, 1, 2, 3, 4, 5]] est : [[0], [1], [2], [3], [4], [5]]
La transposée de [[0], [1], [2], [3], [4], [5]] est : [[0, 1, 2, 3, 4, 5]]
La transposée de [[10, 11, 12], [13, 14, 15], [16, 17, 18]] est : [[10, 13, 16], [11, 14, 17], [12, 15, 18]]


# I. Analyse de graphes à partir d'exemples
## I.1 Présentation des graphes exemples
Pour mener les études qui vont suivre, et en particulier pour vérifier la bonne excution des fonctions à construire, nous utiliserons quatre graphes (notés `G` pour **G**raphe) dont les noms sont explicites : deux sont orientés (repère `o` pour **o**rienté) et les deux autres ne le sont pas (repère `no` pour **n**on-**o**rienté). Pour gérer ces graphes de natures différentes, les sommets seront repérés de deux manières :
1. avec des identifiants **num**ériques (repères `Num`) ;
2. avec des identifiants **alph**anumériques (repères `Alpha`) utilisant des chaînes de caractères.

Dans le cas d'identifiants numériques, des listes et des matrices (listes de listes) seront employées pour coder les graphes. Dans l'autre cas (alphanumérique), une nouvelle structure de données plus appropriée sera présentée et mise enoeuvre : les **dictionnaires**.

Les quatres graphes sont illustrés et nommés sur la figure 2.

<center><img src="illustrations/fig02_4graphes.pdf"><br>
Figure 2 – Les quatre graphes employés.</center> 

## I.2 Représentation, codage et traitements des graphes non-orientés
Nous allons construire les objets Python en mesure de représenter les 4 graphes.

Pour représenter un graphe, nous allons utiliser un premier moyen qui exprime les relations entre les sommets.

### I.2.1 Usage d'une liste
>**Définition**
>
>Une **liste d'adjacence** (notée `La`) est une liste dont chaque élément repéré par son index est la liste de ses voisins (i.e. les sommets qui lui sont liés par une arête).
>Puisque les index sont numériques (type `int`), cette liste décrit des graphes dont les sommets sont numériques.
>Même si ce n'est pas une obligation, il est préférable d'indiquer le numéro des sommets dans l'ordre croissant, appelé l'**ordre des sommets**.
>Dans la pratique, pour établir cette liste de listes, procéder de manière systématique en scrutant chaque sommet par ordre croissant pour remplir la liste des numéros de sommet qui lui sont attachés.
>
>Exemple pour le graphe `GnoNum` :

In [15]:
LaGnoNum = [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]

**Q.1** **Rédiger** la ligne de script permettant d'obtenir l'ordre $n$ du graphe à partir de la liste `LaGnoNum`.

In [16]:
# Réponse à Q.1
n = len(LaGnoNum) # Cette longueur est bien le nombre de sommets
print("Nombre de sommets du graphe, c'est à dire son ordre est", str(n)+'.')

Nombre de sommets du graphe, c'est à dire son ordre est 5.


Si les sommets des graphes ne sont pas repérés par des entiers, mais, par exemple, par des chaînes ce qui est notre cas, il n'est pas possible de s'en servir en tant qu'index de la liste d'adjacence. Pour coder le graphe, nous utilisons un **dictionnaire** où les index sont remplacés par des clés de tyte `str`.

### I.2.2 Usage d'un dictionnaire
Un **dictionnaire** (de type `dict` en Python) est une collection d’objets qui permet de rassembler des éléments en les identifiant, non par un index (numéro d’ordre) comme dans les listes ou les chaînes de caractères, mais par une clé. Par conséquent, **les dictionnaires ne sont pas des séquences** : ce sont des **objets construits** ou **mapping** (cartographie) qui dont correspondre des valeurs à des objets arbitraires. 

Par analogie avec un dictionnaire « classique », l’accès à la définition (qui est **la donnée**) d’un mot est obtenue par le mot lui-même (qui est **la clé**).

**Dictionnaire vide**

À l'instar des listes (`[]`) ou des chaînes (`''`), le dictionnaire vide utilise les délimiteurs accolade ouvrante `{` et fermante `}`pour s’écrire : `{}`

Il peut être créé par affectation directe : `DicoVide = {}`

La création par affectation peut aussi utiliser la fonction de conversion `dict()` : `DicoVide = dict()`

**Remarques sur les dictionnaires**

Les clés d’un dictionnaire sont quasiment arbitraires, **sans être pour autant des listes** ou d’**autres dictionnaires**. Mais les chaînes de caractères s'y prêtent très bien. C'est heureux, car, dans notre cas, nous avons besoin de chaînes pour décrire le graphe `GnoAlpha`.

Il est courant d’utiliser les types numériques pour les clés (pour pouvoir effectuer des comparaisons). C'est favorable avec des entiers qui sont codés de manière stricte, mais c'est imprudent avec les flottants car il existe des disparités dans la représentation des valeurs. **L'usage de clés flottantes est donc à proscrire**. 

**Création d'un dictionnaire**

Un dictionnaire est construit en plaçant entre accolades un ensemble d'associations de la forme « clé: valeur » (séparateur `:`) en séparant ces groupements par des virgules :
`monDico = {cle1: valeur1, cle2: valeur3, cle3: valeur3,...}`

**Q.2** **Donner** le script permettant de définir le dictionnaire d'adjacence nommé `DaGnoAlpha` du graphe `GnoAlpha`, puis de l'afficher, ainsi que son ordre.

In [17]:
# Réponse à Q.2
DaGnoAlpha = {"Paris": ["Lyon", "Lille", "Strasbourg", "Bordeaux"], "Lyon": ["Lille", "Paris"], "Lille":  ["Strasbourg", "Paris", "Lyon"],
              "Strasbourg": ["Bordeaux", "Paris", "Lille"], "Bordeaux": ["Paris", "Strasbourg"]}
# Remarquer que si un dictionnaire est défini sur plus d'une ligne, la deuxième est alignée sur `{`.
# Pour une liste, l'alignement serait sur `[`.

In [18]:
# Affichage de DaGnoAlpha
print(DaGnoAlpha, ",\nle dictionnaire représentant le graphe d'ordre", len(DaGnoAlpha))

{'Paris': ['Lyon', 'Lille', 'Strasbourg', 'Bordeaux'], 'Lyon': ['Lille', 'Paris'], 'Lille': ['Strasbourg', 'Paris', 'Lyon'], 'Strasbourg': ['Bordeaux', 'Paris', 'Lille'], 'Bordeaux': ['Paris', 'Strasbourg']} ,
le dictionnaire représentant le graphe d'ordre 5


Grâce à cette nouvelle organisation, nous n'avons plus recours à une représentation numérique des sommets, ils utilisent uniquement leur nom pour montrer les interactions entre eux. Cependant, si les nombres qui sont concis ne servent plus d'intermédiaires, c'est au prix d'un nombre de caractères plus important, mais plus « parlant ».

### I.2.3 Usage de matrices 
Il est possible de développer la représentation d'un graphe en utilisant des matrices :
1. Avec une matrice qui indique les sommets en relation, pour préciser l'**adjacence des sommets** ;
2. Avec une matrice qui indique les arêtes incidentes avec certains sommets, ce qui précise l'**incidence des arêtes**.

#### I.2.3.1 Matrice d'adjacence
Un graphe peut être représenté par sa **matrice d'adjacence**.

>**Définition**
>
>La **matrice d'adjacence** (notée `Ma`) d'un graphe fini disposant de $n$ sommets est une matrice de dimension $n \times n$ dont l'élément $(Ma_{ij})$ est le nombre d'arêtes liant le sommet $i$ au sommet $j$.

**Remarques**
- Pour des graphes simples, orientés ou pas, un élément de la matrice d'adjacence vaut toujours 0 ou 1.
- La matrice d'adjacence d'un graphe est unique. Par conséquent à deux matrices d'adjacence identiques correspondent deux graphes identiques, et réciproquement.
- La matrice d'adjacence d'un graphe non-orienté est symétrique (mais ce n'est pas le cas pour un graphe orienté).
- Un élément diagonal $a_{ii}$ précise le nombre de boucles du sommet $i$, mais pour les graphes simples, comme il n'y a pas de boucle, $a_{ii}$ vaut systématiquement `1`.

En guise d'application, nous allons coder le graphe `GnoNum` en Python avec une liste de listes (une matrice), puis un tableau `NumPy` (`array`).

**Q.3** **Écrire** sur feuille la matrice d'adjacence `MaGnoNum` du graphe `GnoNum`.

> $$MaGnoNum=
\begin{pmatrix}
   0 & 1 & 1 & 0 & 1 \\
   1 & 0 & 1 & 0 & 0 \\
   1 & 1 & 0 & 1 & 1 \\
   0 & 0 & 1 & 1 & 1 \\
   1 & 0 & 1 & 1 & 0
\end{pmatrix}$$

**Remarque**
- La matrice d'adjacence d'un graphe non-orientée est toujours symétrique.

**Q.4** Pourquoi ne code-t-on pas aussi le graphe `GnoAlpha` avec ce genre de matrice ? Quelle adaptation réaliser pour le faire malgré tout ?
> Le graphe `GnoAlpha` contient des sommets non numériques nommés par des chaînes de caractères. Pour le coder, il faut un objet Python en mesure d'accéder aux données, les arêtes, avec des identifiants non-numériques **comme le permet un dictionnaire**.
> Si toutefois, nous voulons avoir recours à des identifiants numériques, il faut construire une table de correspondance telle que celle-ci :
>
>| Nom du sommet<br/>(chaîne de caractères) | Repère numérique<br/>associé |
>|---------------|:--------------------------:|
>| 'Lille'  | 0 | 
>| 'Lyon' | 1 |
>| 'Paris' | 2 |
>| 'Bordeaux' | 3 | 
>| 'Strasbourg' | 4 |


#### I.2.3.2 Matrice d'incidence
Un graphe peut aussi être représenté par sa **matrice d'incidence**.

>**Définition**
>
>La **matrice d'incidence** (notée `Mi`) d'un graphe fini comprenant $n$ sommets et $m$ arêtes est une matrice de dimension $n \times m$ (rappel : lignes X colonnes) dont l'élément $mi_{ij}$ est le nombre d'incidences entre le sommet $i$ et l'arête $j$.

Ainsi :
- Pour des graphes simples non-orientés, un élément de la matrice d'adjacence vaut toujours 0 ou 1.
- La matrice d'incidence d'un graphe est unique. Par conséquent à deux matrices d'indidence identiques correspondent deux graphes identiques, et réciproquement.

**Q.5** **Écrire** sur feuille la matrice d'incidence `MiGnoNum` du graphe `GnoNum`.

> $$MiGnoNum=
  \begin{pmatrix}
   1 & 0 & 0 & 0 & 1 & 1 & 0 \\
   1 & 1 & 0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 1 & 0 & 0 & 1 & 1 \\
   0 & 0 & 1 & 1 & 0 & 0 & 0 \\
   0 & 0 & 0 & 1 & 1 & 0 & 1
\end{pmatrix}$$

**Remarque**
- Nous pouvons constater que la somme des termes de chaque colonne de la matrice d'adjacence d'un graphe non-orientée vaut deux car une colonne code une arête comportant toujours deux extrémités (pour un graphe simple, mais pas pour un multigraphe).

**Bilan**

Pour achever cette partie, les représentations des graphes au travers de listes et de matrices serviront par la suite à contrôler le bon comportement des fonctions élaboréesq en fournissant des résultats fonformes

### I.2.4 Fonctions de traitement des graphes non-orientés

Les traitements des graphes non-orientés abordés ici utilisent leur représentation par les listes et les matrices définies. ce sera aussi l'occasion d'utiliser `NumPy`, mais moins des dictionnaires.

#### I.2.4.1 liste d'adjacence vs. matrice d'adjacence

**Q.6** **Créer** un script de la fonction dont le protype est :

`def La2Ma(La: list of list) -> matrix:`

recevant la liste d'adjacence `La` d'un graphe non-orienté et renvoyant la matrice d'adjacence. Cette fonction ne doit permettre aucun affichage. Si, pour une raison quelconque, la conversion n'est pas possible, la fonction renverra `None`.

**Indications de conception** pour deux méthodes appelées V1 ou V2)

In [19]:
# Réponse(s) Q.6
def La2Ma(La): # V1 - Conversion d'une liste d'adjacence d'un graphe non-orienté en matrice d'adjacence
    """CE : aL = liste d'adjacence du graphe G (rappel : 1 seule Ma pour un graphe donné).
    CS : matrice d'adjacence du graphe.
    Conversion d'une liste d'adjacence en sa matrice d'adjacence avec méthode append."""
    if not (len(La) != len(La[0])): # Vérif. mat non carrée
        return # Ce n'est pas une matrice d'adjacence
    n = len(La) # n = nbre de sommets du graphe
    Ma = [] # Initialisation matrice d'adjacence
    for i in range(n): # Scrutation lignes
        MaLine = [0]*n # initialisation ligne de Gmat
        for j in La[i]: # Scrutation colonnes
            MaLine[j] = 1 # Positionnement des sommets
        Ma.append(MaLine)        
    return Ma

def La2Ma2(La): # V2 - Conversion d'une liste d'adjacence d'un graphe non-orienté en matrice d'adjacence
    """CE : aL = liste d'adjacence du graphe G (rappel : 1 seule Ma pour un graphe donné).
    CS : matrice d'adjacence du graphe.
    Conversion d'une liste d'adjacence en sa matrice d'adjacence par substitution de 0 en 1."""
    if not (len(La) != len(La[0])): # Vérif. mat non carrée
        return # Ce n'est pas une matrice d'adjacence
    n = len(La) # n = nbre de sommets du graphe
    Ma = [[0]*n for k in range(n)] # Initialisation matrice d'adjacence 
    for i in range(n): # Scrutation de lignes
        for j in La[i]: # Scrutation indices de colonnes
            Ma[i][j] = 1 # Positionnement du sommet en colonne j
    return Ma

**Q.7** **Rédiger** un script, **sans définir de fonction**, qui s'applique au cas de la liste `LaGnoNum` du §I.2.1 pour afficher le résultat avec `matrixDisplay()` et avec la fonction `array()` de `NumPy` (prévoir l'importation du module).

In [20]:
# Réponse Q.7 : mise en oeuvre de La2Ma() et La2Ma2() pour vérification
print('Pour la liste d\'adjacence :', LaGnoNum)
print('V1 - La matrice d\'adjacence est :')
matrixDisplay(La2Ma(LaGnoNum))
Ma = La2Ma2(LaGnoNum)
print('V2 - La matrice d\'adjacence est :')
matrixDisplay(Ma)
print('Avec NumPy, la matrice d\'adjacence apparaît comme ceci :')
import numpy as np
print(np.array(Ma))

Pour la liste d'adjacence : [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]
V1 - La matrice d'adjacence est :
0	1	1	0	1	
1	0	1	0	0	
1	1	0	1	1	
0	0	1	0	1	
1	0	1	1	0	
V2 - La matrice d'adjacence est :
0	1	1	0	1	
1	0	1	0	0	
1	1	0	1	1	
0	0	1	0	1	
1	0	1	1	0	
Avec NumPy, la matrice d'adjacence apparaît comme ceci :
[[0 1 1 0 1]
 [1 0 1 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [1 0 1 1 0]]


#### I.2.4.2 liste et matrice d'adjacence vs. liste des arêtes
**Q.8** **Créer** un script de la fonction dont le protype est :

`def La2Le(La: list of list) -> list of list:`

recevant la liste d'adjacence `La` d'un graphe non-orienté et renvoyant la liste de ses arêtes. Pour rappel une arête est une liste à deux éléments contenant les numéros de ses sommets extrémités. Cette fonction ne doit permettre aucun affichage. Si, pour une raison quelconque, la conversion n'est pas possible, la fonction renverra `None`.

**Compléter** à la suite par un script de quelques lignes permettant de vérifier cette fonction comme à la question Q.7 (pour des listes, `Numpy`. n'est pas utile ici).

In [21]:
# Réponse Q.8
def La2Le(La): # Construction de la liste des arêtes Le à partir de la liste d'adjacence La d'un graphe non-orienté
    """CE : La = Liste d'adjacence d'un graphe non-orienté (rappel : 1 seule liste d'adjacence pour un graphe donné).
    CS : Liste des arêtes du graphe.
    Conversion d'une liste d'adjacence d'un graphe en sa liste des arêtes."""
    if not (type(La) == list and type(La[0]) == list): # aLst = liste d'adj correctement formée ?
        return 
    n = len(La) # n = nbre de sommets du graphe
    Le = [] # Initialisation de la liste des arêtes
    for i in range(n): # Scrutation sommets
        for j in La[i]: # Scrutation  des indices des sommets adjacents du sommet i
            if j >= i: # > Pour éviter les doublons et = pour inclure la diagonale (boucles) = triangle inf.
                Le.append([i, j]) # Ajoute l'arête
    return Le

In [22]:
# Mise en oeuvre de La2Le() pour vérification
print('Pour la liste d\'adjacence du graphe non-orienté :', LaGnoNum)
print('La liste des arêtes obtenue est :', La2Le(LaGnoNum))

Pour la liste d'adjacence du graphe non-orienté : [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]
La liste des arêtes obtenue est : [[0, 1], [0, 2], [0, 4], [1, 2], [2, 3], [2, 4], [3, 4]]


Une alternative consiste à partir de la matrice d'adjacence pour construire la liste des arêtes.

**Q.9** **Créer** un script de la fonction dont le protype est :

`def Ma2Le(Ma: matrix) -> list of list:`

recevant la matrice d'adjacence `Ma` d'un graphe non-orienté et renvoyant la liste de ses arêtes. Cette fonction ne doit permettre aucun affichage. Si, pour une raison quelconque, la conversion n'est pas possible, la fonction renverra `None`.

**Compléter** par un script de quelques lignes permettant de vérifier cette fonction.

In [23]:
# Réponse Q.9
def Ma2Le(Ma): # Construction de la liste des arêtes (Le) à partir de la matrice d'adjacence Ma
    """CE : Matrice d'adjacence Ma d'un graphe non-orienté (rappel : 1 seule Ma pour un graphe donné).
    CS : Liste des arêtes du graphe.
    Conversion d'une matrice d'adjacence d'un graphe en sa liste des arêtes."""
    if not isMatrix(Ma) or len(Ma) != len(Ma[0]): # Ma = matrice correctement formée
        return
    n = len(Ma) # n = nbre de sommets du graphe
    Le = [] # Initialisation de la liste des arêtes
    for i in range(n): # Scrutation lignes
        for j in range(i, n): # Scrutation des colonnes au delà de i pour éviter les doublons
            if Ma[i][j]: # Test d'adjacence (1 == Vrai)
                Le.append([i, j]) # Ajoute l'arête
    return Le

In [24]:
# Mise en oeuvre de Ma2Le() pour vérification
print('Pour la matrice d\'adjacence du graphe non-orienté :')
Ma = La2Ma(LaGnoNum)
matrixDisplay(Ma)
print('La liste des arêtes est :', Ma2Le(Ma))

Pour la matrice d'adjacence du graphe non-orienté :
0	1	1	0	1	
1	0	1	0	0	
1	1	0	1	1	
0	0	1	0	1	
1	0	1	1	0	
La liste des arêtes est : [[0, 1], [0, 2], [0, 4], [1, 2], [2, 3], [2, 4], [3, 4]]


#### I.2.4.3 Construction de la matrice d’incidence
La matrice d'incidence d'un graphe non-orienté peut être obtenue de différentes manières :
- à partir de la liste des sommets (La) et des arêtes du graphe (Le) qui constitue la méthode la plus simple ;
- à partir de la seule liste des sommets ou des arêtes du graphe, ce qui nécessite de reconstituer les deux entrées de la matrice (sommets et arêtes) ; 
- à partir de la matrice d'adjacence.

Puisque la fonction `La2Ma()` permet de construire la matrice d'adjacence, nous n'utiliserons que cette seule matrice comme source pour établir la matrice d'incidence. Rien n'exclue de traiter les deux autres fonctions (La & Le -> Mi et La|Le -> Mi).

**Q.10** **Créer** un script pour chacune des fonctions définies ci-dessous :

`def La2Mi(La: list of list) -> matrix:`

recevant la liste d'adjacence `La` d'un graphe non-orienté et renvoyant sa matrice d'incidence.

`def Ma2Mi(Ma: matrix) -> matrix:`

recevant la matrice d'adjacence `Ma` d'un graphe non-orienté et renvoyant sa matrice d'incidence. L'usage de la fonction `Ma2Le()` sera à considérer.

Dans les deux cas, les fonctions ne doivent permettre aucun affichage. Si, pour une raison quelconque, la conversion n'est pas possible, les fonction renverront `None`.

**Compléter** par un script de quelques lignes permettant de vérifier ces fonctions en favorisant l'usage de `NumPy`.

In [25]:
# Réponse Q.10
def La2Mi(La): # Conversion d'une liste d'adjacence d'un graphe non-orienté en sa matrice d'incidence
    """CE : La = liste d'adjacence du graphe non-orienté (rappel : 1 seule Ma pour un graphe donné).
    CS : matrice d'incidence du graphe.
    Conversion de la liste d'adjacence d'un graphe non-orienté en sa matrice d'incidence avec méthode append."""
    Le = La2Le(La) # Liste des arêtes du graphe
    n, m = len(La), len(Le) # n = nbre de sommets du graphe, m = nbre d'arêtes
    Mi = [] # Initialisation matrice d'incidence
    for i in range(n): # Scrutation lignes de Ma
        MiLine = [0]*m # initialisation ligne de Mi
        for j in range(m): # Scrutation colonnes de Mi
            if i in Le[j]: # Test d'incidence
                MiLine[j] = 1     
        Mi.append(MiLine) # Ajout à Mi de la ligne construite 
    return Mi

def Ma2Mi(Ma): # Conversion d'une matrice d'adjacence d'un graphe non-orienté en sa matrice d'incidence
    """CE : Ma = matrice d'adjacence du graphe non-orienté (rappel : 1 seule Ma pour un graphe donné).
    CS : matrice d'incidence du graphe.
    Conversion de la matrice d'adjacence d'un graphe non-orienté en sa matrice d'incidence avec méthode append."""
    Le = Ma2Le(Ma) # Liste des arêtes du graphe
    n, m = len(Ma), len(Le) # n = nbre de sommets du graphe, m = nbre d'arêtes
    Mi = [] # Initialisation matrice d'incidence
    for i in range(n): # Scrutation lignes de Ma
        MiLine = [0]*m # initialisation ligne de Mi
        for j in range(m): # Scrutation colonnes de Mi
            if i in Le[j]: # Test d'incidence
                MiLine[j] = 1     
        Mi.append(MiLine) # Ajout à Mi de la ligne construite 
    return Mi

In [26]:
# Mise en oeuvre de La2Mi() et Ma2Mi() pour vérification
print('Pour la liste d\'adjacence (graphe non-orienté) :', LaGnoNum)
print('La matrice d\'incidence est :')
Mi1 = La2Mi(LaGnoNum)
print(np.array(Mi1))
print('Pour la matrice d\'adjacence (graphe non-orienté) :')
Ma = La2Ma(LaGnoNum)
print(np.array(Ma))
print('La matrice d\'incidence est :')
Mi2 = Ma2Mi(Ma)
print(np.array(Mi2))
print('Résultats identiques ?', Mi1 == Mi2)

Pour la liste d'adjacence (graphe non-orienté) : [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]
La matrice d'incidence est :
[[1 1 1 0 0 0 0]
 [1 0 0 1 0 0 0]
 [0 1 0 1 1 1 0]
 [0 0 0 0 1 0 1]
 [0 0 1 0 0 1 1]]
Pour la matrice d'adjacence (graphe non-orienté) :
[[0 1 1 0 1]
 [1 0 1 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [1 0 1 1 0]]
La matrice d'incidence est :
[[1 1 1 0 0 0 0]
 [1 0 0 1 0 0 0]
 [0 1 0 1 1 1 0]
 [0 0 0 0 1 0 1]
 [0 0 1 0 0 1 1]]
Résultats identiques ? True


### I.2.5 Bilan, conclusion
Les trois représentations (liste, dictionnaire et matrice avec un liste de listes ou un tableau `NumPy`) ont des occupations mémoire variables. Les listes et les dictionnaires ne mentionnent que les sommets en relation en eux, tandis que les matrices mentionnent tous les liens possible s en ne sélectionnat (par un 1) ceux qui sont effectifs. Notons d'ailleurs qu'un graphe complet à $n$ sommets comporte $n^2$ arêtes : la **complexité spatiale d'une matrice est donc quadratique**.

Nous pouvons conclure en affirmant que la représentation matricielle des graphes est plus gournmande en espace mémoire qu'avec des listes où des dictionnaires. Cependant la lecture des informations dans la matrice d'adjacence est plus simple et directe à appréhender que dans les autres cas où elle apparaît comme codée, donc compressée, pour les deux autres représentations.

## I.3 Représentation, codage et traitements des graphes orientés
Nous étendons maintenant les études précédentes aux graphes orientés.

Le plan de cette partie reprend celui du §I.2 pour énoncer les questions relatives à la construction de nouvelle fonctions appliquées à des graphes orientées.

Les graphes supports sont maintenant orientés : `GoNum` et `GoAlpha` (`o` à la place de `no`).

### I.3.1 Liste d'adjacence
Pour un graphe orienté, l'adjacence de deux sommets n'est pas réciproque. Il faut se référer à l'orientation imposée par la flèche comme le précise le § `I.2.1`.

Pour le graphe `GoNum` :

In [32]:
LaGoNum = [[1, 4], [], [0, 1, 3, 4], [], [3]]

Nous pouvons noter que `LaGoNum` contient (naturellement) moins de sommets en relation que `LaGnoNum` : des liens disparaissent en raison de l'orientation des arêtes.

### I.3.2 Dictionnaire d'adjacence

**Q.11** **Donner** le script permettant de définir le dictionnaire d'adjacence nommé `DaGoAlpha` du graphe `GoAlpha`. 
**Compléter** ce script pour afficher le dictionnaire et l'ordre du graphe.

In [33]:
DaGoAlpha = {"Paris": ["Lyon", "Lille", "Strasbourg", "Bordeaux"], "Lyon": [], "Lille":  ["Strasbourg", "Lyon"],
              "Strasbourg": ["Bordeaux"], "Bordeaux": []}
print('Le dictionnaire :', DaGoAlpha, "\ncorrespond à un graphe d'ordre",len(DaGoAlpha))

Le dictionnaire : {'Paris': ['Lyon', 'Lille', 'Strasbourg', 'Bordeaux'], 'Lyon': [], 'Lille': ['Strasbourg', 'Lyon'], 'Strasbourg': ['Bordeaux'], 'Bordeaux': []} 
correspond à un graphe d'ordre 5


### I.3.3 Matrice d'adjacence

>**Rappel**
>
>Nous noterons toujours, de manière générale, `Ma` une matrice d'adjacence et $n$ son nombre de sommets.
>
>La construction de la matrice d'adjacence s'appuiera toujours sur la liste d'adjacence.

**Q.12** **Écrire** sur feuille la matrice d'adjacence `MaGoNum` du graphe `GoNum`.

> $$MaGoNum=
\begin{pmatrix}
   0 & 1 & 0 & 0 & 1 \\
   0 & 0 & 0 & 0 & 0 \\
   1 & 1 & 0 & 1 & 1 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 0 & 0 & 1 & 0
\end{pmatrix}$$

### I.3.4 Matrice d'incidence

Sur la base de la définition du §I.2.3.2, le sens de l'incidence aux sommets influence les coefficients de la matrice :
- si une arête arrive sur un sommet, le coefficient est -1 ;
- si une arête sort d'un sommet, le coefficient est 1 ;
- s'il n'y a pas d'incidence, le coefficient vaut 0.

**Q.13** **Écrire** sur feuille la matrice d'incidence `MiGoNum` du graphe `GoNum` (utiliser l'ordre systématique des arêtes).

> $$MiGoNum=
\begin{pmatrix}
    1 &  1 & -1 &  0 &  0 &  0 &  0 \\
   -1 &  0 &  0 & -1 &  0 &  0 &  0 \\
    0 &  0 &  1 &  1 &  1 &  1 &  0 \\
    0 &  0 &  0 &  0 & -1 &  0 & -1 \\
    0 & -1 &  0 &  0 &  0 & -1 &  1
\end{pmatrix}$$

**Q.14** Quelle remarque peut-on faire concernant la somme des termes d'une colone de $MiGoNum$ ? **Justifier**. En **déduire** un moyen de contrôler la matrice d'incidence d'un graphe orienté. 

>La somme des termes de chaque colonne de $MiGoNum$ est nulle. Ceci est dû au fait que chaque colonne correspond à une arête composée d'une queue affectée de la veleur 1 et d'une tête affectée de la valeur -1 dont la somme est nulle. Par conséquent, pour **vérifier qu'une matrice d'adjacence est celle d'un graphe orienté**, il faut **vérifier la nullité de la somme de tous les termes de chacune de ses colonnes**.

### I.3.5 Fonctions de traitement des graphes orientés
Pour les traitements des graphes orientés, nous utiliserons le plus possible `NumPy`.

#### I.3.5.1 Construction de la matrice d'adjacence

**Q.15** **Créer** un script de la fonction dont le protype est :

`def La2MaO(La: list of list) -> matrix:`

recevant la liste d'adjacence `La` d'un graphe orienté et renvoyant la matrice d'adjacence. Cette fonction ne doit permettre aucun affichage. Si, pour une raison quelconque, la conversion n'est pas possible, la fonction renverra `None`.

**Remarque** – Noter l'ajout de `O` (l'initiale d'**O**rienté, pas le chiffre zéro) au nom de la fonction traitant d'un graphe non-orienté pour la distinguer.

In [34]:
# Réponse Q.15
def La2MaO(La): # Conversion d'une liste d'adjacence d'un graphe orienté en sa matrice d'adjacence
    """CE : La = liste d'adjacence du graphe.
    CS : matrice d'adjacence du graphe orienté.
    Conversion d'une liste d'adjacence en sa matrice d'adjacence par substitution de 0 en 1."""
    if not (len(La) != len(La[0])): # Vérif. mat non carrée
        return None # Ce n'est pas une matrice d'adjacence
    n = len(La) # n = nbre de sommets du graphe = ordre du graphe (rappel)
    Ma = [[0]*n for k in range(n)] # Initialisation matrice d'adjacence 
    for i in range(n): # Scrutation de lignes
        for j in La[i]: # Scrutation indices de colonnes
            Ma[i][j] = 1 # Positionnement du sommet en colonne j
    return Ma

**Q.16** **Rédiger** un script, **sans définir de fonction**, qui s'applique au cas de la liste `LaGoNum` du §`I.3.1` pour afficher le résultat avec la fonction `array()` de `NumPy`.

In [35]:
# Réponse Q.16 : mise en oeuvre de La2MaO() pour vérification
print('Pour la liste d\'adjacence du graphe orienté :', LaGoNum)
Ma = La2MaO(LaGoNum)
print('La matrice d\'adjacence est :')
import numpy as np
print(np.array(Ma))

Pour la liste d'adjacence du graphe orienté : [[1, 4], [], [0, 1, 3, 4], [], [3]]
La matrice d'adjacence est :
[[0 1 0 0 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [0 0 0 1 0]]


#### I.3.5.2 Construction de la liste des arêtes
La liste des arêtes est toujours construite à partir de la liste d'adjacence, mais en tenant compte de leur orientation. Pour la prendre en compte, la liste d'adjacence formulée d'une nouvelle manière pour faire référence aux arêtes :
>la liste d'adjacence d'un graphe orienté est la liste des couples dont le premier terme est le sommet à la queue de l'arête et le second, le sommet à sa tête (figure 3).

<center><img src="illustrations/fig03_OrientationArete.pdf"><br>
Figure 3 – Arête orientée.</center>

**Q.17** Sur la base de la formulation précédente, **créer** un script de la fonction dont le protype est :

`def La2LeO(La: list of list) -> list of list:`

recevant la liste d'adjacence `La` d'un graphe orienté et renvoyant la liste de ses arêtes. Cette fonction ne doit permettre aucun affichage. Si, pour une raison quelconque, la conversion n'est pas possible, la fonction renverra `None`.

**Remarque** – Dans le cas cas des graphes non-orientés, la construction de cette liste nécessitait de ne pas prendre en compte les arêtes deux fois. Revenir sur cette considération dans le cas des graphes orientés. 

**Compléter** à la suite par un script de quelques lignes permettant de vérifier cette fonction.

In [36]:
# Réponse Q.17
def La2LeO(La): # Construction de la liste des arêtes Le à partir de la liste d'adjacence La d'un graphe orienté
    """CE : La = Liste d'adjacence d'un graphe orienté
    CS : Liste des arêtes du graphe.
    Conversion d'une liste d'adjacence d'un graphe orienté en sa liste des arêtes."""
    if not (type(La) == list and type(La[0]) == list): # aLst = liste d'adj correctement formée ?
        return 
    n = len(La) # n = nbre de sommets du graphe
    Le = [] # Initialisation de la liste des arêtes
    for i in range(n): # Scrutation sommets
        for j in La[i]: # Scrutation  des indices des sommets adjacents du sommet i
            Le.append([i, j]) # Ajoute l'arête avec la bonne orientation
    return Le

In [37]:
# Mise en oeuvre de La2LeO() pour vérification
print('Pour la liste d\'adjacence du graphe orienté :', LaGoNum)
print('La liste des arêtes obtenue est :', La2LeO(LaGoNum))

Pour la liste d'adjacence du graphe orienté : [[1, 4], [], [0, 1, 3, 4], [], [3]]
La liste des arêtes obtenue est : [[0, 1], [0, 4], [2, 0], [2, 1], [2, 3], [2, 4], [4, 3]]


#### I.3.5.3 Construction de la matrice d’incidence

**Q.18** Nous nous basons ici sur la liste d'adjacence des graphes non-orientés pour **créer** un script de la fonction dont le protype est :

`def La2MiO(Ma: list of list) -> matrix:`

recevant la liste d'adjacence `La` d'un graphe orienté et renvoyant sa matrice d'incidence. Les contraintes de construction seront les mêmes que pour les fonctions déjà traitées. 

**Remarque**
1. Concevoir cette fonction en utilisant des tableaux `NumPy` (array).
2. Prendre en compte la tête (indice 1) et la queue (indice 0) des arêtes pour attribuer des valeurs `1` ou `-1` aux termes de la matrice d'incidence. 

**Compléter** par un script de quelques lignes permettant de vérifier cette fonction. Privilégier l'usage de `Numpy`.

In [39]:
def La2MiO(La): # Conversion d'une liste d'adjacence d'un graphe orienté en sa matrice d'incidence
    """CE : La = liste d'adjacence du graphe orienté.
    CS : matrice d'incidence du graphe.
    Conversion de la liste d'adjacence d'un graphe orienté en sa matrice d'incidence avec la méthode append."""
    Le = La2LeO(La) # Liste des arêtes orientées du graphe
    n, m = len(La), len(Le) # n = nbre de sommets du graphe, m = nbre d'arêtes
    Mi = np.zeros((n, m), dtype='int') # Initialisation de la matrice d'incidence
    for j in range(m): # D'abord scrutation des colonnes de Mi (ie, les arêtes)
        for i in range(n): # Puis scrutation des lignes de La (ie, les sommets)
            if Le[j][0] == i: # La queue
                Mi[i, j] = 1 
            elif Le[j][1] == i: # La tête
                Mi[i, j] = -1 
            else: # Pas de coïncidence
                Mi[i, j] = 0    
    return Mi

In [40]:
# Mise en oeuvre de La2MiO() pour vérification
print('Pour la liste d\'adjacence (graphe orienté) :')
print(LaGoNum)
print('La liste d\'incidence est :', La2LeO(LaGoNum))
print('La matrice d\'incidence est :')
MiO = La2MiO(LaGoNum)
print(np.array(MiO))

Pour la liste d'adjacence (graphe orienté) :
[[1, 4], [], [0, 1, 3, 4], [], [3]]
La liste d'incidence est : [[0, 1], [0, 4], [2, 0], [2, 1], [2, 3], [2, 4], [4, 3]]
La matrice d'incidence est :
[[ 1  1 -1  0  0  0  0]
 [-1  0  0 -1  0  0  0]
 [ 0  0  1  1  1  1  0]
 [ 0  0  0  0 -1  0 -1]
 [ 0 -1  0  0  0 -1  1]]


# II. Fonctions de caractérisation des graphes
Cette partie propose de créer différentes fonctions :
1. pour effectuer des vérifications sur les listes, dictionnaires et matrices représentant des graphes pour illustrer leurs différentes proprités.
2. mettre oeuvre les définitions établies en cours (diaporama « Éléments de base sur les graphes » diponible sur l'ENT Moodle) et dans la partie `I.` précédente.

À terme, il est possible d'envisager de concevoir un script de fonction à laquelle serait passé la liste d'adjacence d'un graphe pour renvoyer une fiche des propriétés de ce graphe.

## II.1 Symétrie de la matrice d'adjacence d'un graphe non-orienté
Nous avons constaté (§`I.2.3.1`) que la matrice d'adjacence d'un graphe non-orientée est toujours symétrique. Cette propriété peut permettre de vérifier que le graphe associé à une matrice symétrique est non-orienté.

**Q.19** **Créer** un script de la fonction dont le protype est :

`def isSymmetric(M: matrix) -> bool:`

recevant une matrice `M` et renvoyant `True` si elle est carrée et symétrique et False `sinon`, donc susceptible de représenter un graphe non-orienté. Comme toujours, vette fonction ne doit permettre aucun affichage. Si, pour une raison quelconque, les traitements ne sont pas en mesure d'établir une valeur de vérité, la fonction renverra `None`.

**Remarque** - Lors de la scrutation des élements de la matrice, il faudra être attentif à ne tester l'égalité des éléments diagonaux qu'**une seule fois**.

Pour terminer, **concevoir** à la suite par un script de quelques lignes permettant de vérifier que cette fonction valide bien la symétrie du résultat renvoyé par la fonction `La2Ma()` du graphe `GnoNum`.

In [41]:
# Question Q.19
def isSymmetric(M):
    if type(M) != list:
        return None # Si l'argument n'est pas une liste, pas la peine
    else:
        if type(M[0]) != list: # idem pour la première ligne, pas la peine
            return None
        else: # ici c'est une liste de listes
            for l in M:
                if len(l) != len(M[0]): # Une ligne de taille différente : pas une matrice
                    return None
            if len(M) != len(M[0]): # Nbre ligne différent du Nbre de colonne
                return None # Pas la peine
    # A partir d'ici la matrice est est carrée
    n = len(M) # Taille matrice
    for i in range(n):
        for j in range(i, n):
            if M[i][j] != M[j][i]:
                return False
    return True

In [42]:
# Mise en oeuvre de isSymmetric() pour vérification
LaGnoNum = [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]
print('Pour la liste d\'adjacence :', LaGnoNum)
Ma = La2Ma(LaGnoNum)
print('La matrice d\'adjacence est :\n', np.array(Ma))
print('Est-elle symétrique ? ', isSymmetric(Ma))
Mns = list(Ma) # initialisation d'une représentation non symétrique
Mns[1][0] = 2 # Insersion d'une dissymétrie
print('La matrice :\n', np.array(Mns))
print('Est-elle symétrique ?', isSymmetric(Mns))

Pour la liste d'adjacence : [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]
La matrice d'adjacence est :
 [[0 1 1 0 1]
 [1 0 1 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [1 0 1 1 0]]
Est-elle symétrique ?  True
La matrice :
 [[0 1 1 0 1]
 [2 0 1 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [1 0 1 1 0]]
Est-elle symétrique ? False


## II.2 Détection de la cohérence d'un graphe (orienté ou pas) par sa matrice d'incidence
Chaque colonne d'une matrice d'incidence d'un graphe code une seule arête comportant toujours deux extrémités, par conséquent, on y observe toujours :
- deux `1` pour un graphe non-orienté,
- un terme `-1` et un `1` pour un graphe orienté.

Nous pouvons alors en déduire que la somme des termes de chacune de ses colonnes vaut :
- **2** pour un graphe non-orienté,
- **0** pour un graphe orienté.

Ceci nous renseigne sur la nature et la cohérence des termes d'une matrice d'incidence.

**Q.20** **Créer** un script de la fonction dont le protype est :

`def isImatrix(M: matrix) -> 'no'|'o':`

recevant une matrice d'incidence `M` et renvoyant `'no'` si la matrice `M` est possiblement la matrice d'incidence d'un graphe non-orienté ou `'o'` si c'est celle d'un graphe orienté. Pour les autres cas, incluant les incohérences (par exemple si `M` n'est pas une matrice), `None` sera renvoyé.

**Utiliser** NumPy autant que possible en commençant par convertir la liste `M` en tableau `NumPy` par : `M = np.array(M)`.

**Mettre en oeuvre** les essais de la fonction avec les différentes matrices définies.

In [43]:
# Question Q.20
def isImatrix(M): # Avec NumPy - - - - - - - à revoir
    if not isMatrix(M):
        return
    # À partir d'ici, M est une matrice 'bien formée'
    M = np.array(M, dtype=int) # Conversion de M en NumPy
    n, m = np.shape(M) # Extraction des tailles de M
    mdl = np.ones(m, dtype=int) # Ligne de sommation type
    lSum = np.sum(M, axis = 0) # Sommation par les colonnes
    print('Sommation lSum / mdl', lSum, '/', mdl, ' - isMatrix()')
    if (lSum == mdl*2).all():
        return 'no'
    elif (lSum == mdl*0).all():
        return 'o'
    return None # Pour les autres cas

def isImatrix2(M): # Sans NumPy - - - - - - - à revoir
    if not isMatrix(M):
        return
    # À partir d'ici, M est une matrice 'bien formée'
    n, m = len(M), len(M[0]) # Extraction des tailles de M
    mdl2 = [2]*m # Ligne de sommation type graphe non-orienté
    mdl0 = [0]*m # Ligne de sommation type graphe orienté
    lSum = [0]*m # Initialisation de la sommation des colonnes
    for j in range(m): # Sommation par colonnes
        s = 0
        for i in range(n):
            s += M[i][j]
        lSum[j] = s
    print('Sommation lSum / mdl', lSum, '/', mdl2, ' - isMatrix2()')
    if lSum == mdl2:   # Ligne de 2...
        return 'no'     # ... Pour les graphes non-orientés
    if lSum == mdl0: # Ligne de 0...
        return 'o'      #... Pour les graphes orientés
    return None         # Pour les autres cas

In [44]:
# Mise en oeuvre de isImatrix() pour vérification
LaGnoNum = [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]] # Rappel de GnoNum
print('Pour la liste d\'adjacence :', LaGnoNum)
Mi = La2Mi(LaGnoNum)
print('La matrice d\'incidence est :\n', np.array(Mi))
print(' Cette matrice d\'incidence est-elle cohérente pour un graphe non-orienté (NumPy) ? ', isImatrix(Mi))
print('Cette matrice d\'incidence est-elle cohérente pour un graphe non-orienté (Python) ? ', isImatrix2(Mi))

LaGoNum = [[1, 4], [], [0, 1, 3, 4], [], [3]] # Rappel de GoNum
print('\nPour la liste d\'adjacence :', LaGoNum)
MiO = La2MiO(LaGoNum) # Fonction des graphes orientés
print('La matrice d\'incidence est :\n', np.array(MiO))
print(' Cette matrice d\'incidence est-elle cohérente pour un graphe orienté (NumPy) ? ', isImatrix(MiO))
print('Cette matrice d\'incidence est-elle cohérente pour un graphe orienté (Python) ? ', isImatrix2(MiO))

Pour la liste d'adjacence : [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]
La matrice d'incidence est :
 [[1 1 1 0 0 0 0]
 [1 0 0 1 0 0 0]
 [0 1 0 1 1 1 0]
 [0 0 0 0 1 0 1]
 [0 0 1 0 0 1 1]]
Sommation lSum / mdl [2 2 2 2 2 2 2] / [1 1 1 1 1 1 1]  - isMatrix()
 Cette matrice d'incidence est-elle cohérente pour un graphe non-orienté (NumPy) ?  no
Sommation lSum / mdl [2, 2, 2, 2, 2, 2, 2] / [2, 2, 2, 2, 2, 2, 2]  - isMatrix2()
Cette matrice d'incidence est-elle cohérente pour un graphe non-orienté (Python) ?  no

Pour la liste d'adjacence : [[1, 4], [], [0, 1, 3, 4], [], [3]]
La matrice d'incidence est :
 [[ 1  1 -1  0  0  0  0]
 [-1  0  0 -1  0  0  0]
 [ 0  0  1  1  1  1  0]
 [ 0  0  0  0 -1  0 -1]
 [ 0 -1  0  0  0 -1  1]]
 Cette matrice d'incidence est-elle cohérente pour un graphe orienté (NumPy) ?  None
Cette matrice d'incidence est-elle cohérente pour un graphe orienté (Python) ?  None


/var/folders/vr/j29hsskd0rd47tmjb3shbhqm0000gn/T/ipykernel_76910/67371436.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if U in ([], [[]]): # Cas de rejets possibles


## II.3 Caractéristiques des sommets d’un graphe
Les représentations les plus simples d'un graphe sont :
- la **liste d'adjacence** pour les graphes numériques ;
- le **dictionnaire d'adjacence** pour les graphes alphanumériques, mais qui peut aussi représenter un graphe numérique, ce qui confère au dictionnaire un mode de représentation très général des graphes.

**Q.21** **Rédiger** un script permettant d'affecter toutes les listes et dictionnaires d'adjacence des 4 graphes exemples. Il y a peu de choses a créer ici, tous ont déjà été définis, il faut juste tout regrouper dans un script de quelques lignes.

**Terminer** par la rédaction d'un script permettant d'afficher tous ces objets.

In [45]:
# Rappel : "Lille" = 0, "Lyon" = 1, "Paris" = 2, "Bordeaux" = 3, "Strasbourg" = 4
LaGnoNum = [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]]
LaGnoAlpha = [["Lyon", "Paris", "Strasbourg"], ["Lille", "Paris"], ["Lille", "Lyon", "Bordeaux", "Strasbourg"],
              ["Paris", "Strasbourg"], ["Lille", "Paris", "Bordeaux"]]
DaGnoAlpha = {"Lille":  ["Lyon", "Paris", "Strasbourg"],
              "Lyon": ["Lille", "Paris"], 
              "Paris": ["Lille", "Lyon", "Bordeaux", "Strasbourg"],
              "Bordeaux": ["Paris", "Strasbourg"],
              "Strasbourg": ["Lille", "Paris", "Bordeaux"]}
LaGoNum = [[1, 4], [], [0, 1, 3, 4], [], [3]]
LaGoAlpha = [["Lyon", "Strasbourg"], [], ["Lille", "Lyon", "Bordeaux", "Strasbourg"], [], ["Bordeaux"]]
DaGoAlpha = {"Lille": ["Lyon", "Strasbourg"],
             "Lyon": [],
             "Paris":  ["Lille", "Lyon", "Bordeaux", "Strasbourg"],
             "Bordeaux": [],
             "Strasbourg": ["Bordeaux"]}

allObjects = (LaGnoNum, LaGnoAlpha, DaGnoAlpha, LaGoNum, LaGoAlpha, DaGoAlpha)
for rank, obj in enumerate(allObjects):
    print(rank, ':', obj, '\n')

0 : [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]] 

1 : [['Lyon', 'Paris', 'Strasbourg'], ['Lille', 'Paris'], ['Lille', 'Lyon', 'Bordeaux', 'Strasbourg'], ['Paris', 'Strasbourg'], ['Lille', 'Paris', 'Bordeaux']] 

2 : {'Lille': ['Lyon', 'Paris', 'Strasbourg'], 'Lyon': ['Lille', 'Paris'], 'Paris': ['Lille', 'Lyon', 'Bordeaux', 'Strasbourg'], 'Bordeaux': ['Paris', 'Strasbourg'], 'Strasbourg': ['Lille', 'Paris', 'Bordeaux']} 

3 : [[1, 4], [], [0, 1, 3, 4], [], [3]] 

4 : [['Lyon', 'Strasbourg'], [], ['Lille', 'Lyon', 'Bordeaux', 'Strasbourg'], [], ['Bordeaux']] 

5 : {'Lille': ['Lyon', 'Strasbourg'], 'Lyon': [], 'Paris': ['Lille', 'Lyon', 'Bordeaux', 'Strasbourg'], 'Bordeaux': [], 'Strasbourg': ['Bordeaux']} 



**Q.22** **Rédiger** un script permettant d'afficher chaque graphe, puis, à la suite chacun de ses sommets sur différentes lignes :
1. l'énumération de ses voisins ;
2. le degré de ce sommet ;
3. à la fin, au-dessous, l'ordre et le degré du graphe.

Le choix de la structure représentative des graphes est laissé libre, mais **manipuler aussi bien des listes que des dictionnaires**.

**Pour rappel**, la recherche du maximun d'un groupe de valeurs a été étudié durant l'année. La méthode consiste à actualiser le maximum avec chaque nouveau degré calculé.

In [46]:
AllGraphs = (LaGnoNum, DaGnoAlpha, LaGoNum, DaGoAlpha)
for rank, obj in enumerate(AllGraphs): # Sur le principe de Q.20.
    order = len(obj) # Ordre du graphe = nbre de sommets = taille de l'objet
    print(rank, '-', obj, ':') # 1. l'énumération de ses voisins
    graphDegree = 0 # Initialisation du degré du graphe
    for vertex in obj: # Scrutation des sommets (toujours des listes) du graphe courant
        if type(obj) == dict:
            vertexDegree = len(obj[vertex]) # vertex est une clé qui pointe vers une donnée liste
        elif type(obj) == list:
            vertexDegree = len(vertex) # vertex est une liste ici         
        if vertexDegree > graphDegree: # Mise à jour du...
            graphDegree = vertexDegree # ...max des degrés = degré du graphe
        print('Sommet', vertex, 'de degré', vertexDegree) # 2. le degré de ce sommet       
    print('- - - Récapitulatif')
    # 3. à la fin, au-dessous, l'ordre et le degré du graphe.    
    print('Ordre du graphe :', order) # Défini plus haut
    print('Degré du graphe :', graphDegree) # Rappel, max des degrés des sommets
    print() # Ligne de séparation

0 - [[1, 2, 4], [0, 2], [0, 1, 3, 4], [2, 4], [0, 2, 3]] :
Sommet [1, 2, 4] de degré 3
Sommet [0, 2] de degré 2
Sommet [0, 1, 3, 4] de degré 4
Sommet [2, 4] de degré 2
Sommet [0, 2, 3] de degré 3
- - - Récapitulatif
Ordre du graphe : 5
Degré du graphe : 4

1 - {'Lille': ['Lyon', 'Paris', 'Strasbourg'], 'Lyon': ['Lille', 'Paris'], 'Paris': ['Lille', 'Lyon', 'Bordeaux', 'Strasbourg'], 'Bordeaux': ['Paris', 'Strasbourg'], 'Strasbourg': ['Lille', 'Paris', 'Bordeaux']} :
Sommet Lille de degré 3
Sommet Lyon de degré 2
Sommet Paris de degré 4
Sommet Bordeaux de degré 2
Sommet Strasbourg de degré 3
- - - Récapitulatif
Ordre du graphe : 5
Degré du graphe : 4

2 - [[1, 4], [], [0, 1, 3, 4], [], [3]] :
Sommet [1, 4] de degré 2
Sommet [] de degré 0
Sommet [0, 1, 3, 4] de degré 4
Sommet [] de degré 0
Sommet [3] de degré 1
- - - Récapitulatif
Ordre du graphe : 5
Degré du graphe : 4

3 - {'Lille': ['Lyon', 'Strasbourg'], 'Lyon': [], 'Paris': ['Lille', 'Lyon', 'Bordeaux', 'Strasbourg'], 'Bordeaux': []

# <center>— Fin du TD « Graphes » —</center>